### ISSUE TITLE
Video player skin design

### ISSUE THREAD

**Issue by ismaelrumzan** [ismaelrumzan/mahad-al-tafsir#14]
Create a custom video player design that fits the brand and logo

**Comment by nuratun** [comment]
OK, first draft is ready for review. 

I've linked it to the Featured Section v4.2. So:

1) Go here first: [Figma](https://www.figma.com/proto/HtXGvDYRnSY28I4VwHNFXQ/Tafsir-Institute?page-id=302%3A1204&node-id=320%3A2221&viewport=416%2C-1331%2C0.25&scaling=scale-down&starting-point-node-id=320%3A2221&show-proto-sidebar=1)

2) Click on any of the classes (or the featured section) to view the playing video

3) Click on the pause button to see what it looks paused 

4) Click the forward button to see the full playlist

**Comment by ismaelrumzan** [comment]
![CleanShot 2022-07-15 at 10 34 43@2x](https://user-images.githubusercontent.com/481891/179268559-3d8e9ded-4cbf-41e4-9d5e-9770d8dca201.png)
![CleanShot 2022-07-15 at 10 39 42@2x](https://user-images.githubusercontent.com/481891/179269188-c06f4684-daf0-42d9-9de5-f21ad1ec7be0.png)
![CleanShot 2022-07-15 at 10 42 57@2x](https://user-images.githubusercontent.com/481891/179269590-894ae576-1618-462b-b793-d88bb45a2a9b.png)

**Comment by ismaelrumzan** [comment]
Not worth the extra work - using React Lite YT player is subtle enough
https://github.com/ismaelrumzan/mahad-al-tafsir/pull/23
In the future we can improve the drop-down to a better playlist picker
