### ISSUE TITLE
Add google analytics

### ISSUE THREAD

**Issue by ismaelrumzan** [ismaelrumzan/mahad-al-tafsir#18]
# Overall Goal: Add google analytics tracking to all pages of the site

Let's break the task in pieces

## Assignment 1
TASK: Implement a basic project with google analytics such as https://github.com/vercel/next.js/tree/canary/examples/with-google-analytics

### Steps
  - Create your own account on vercel.com
  - Create a google analytics tracking ID using your own gmail account
  - Clone the above repo and deploy to Vercel - add your google analytics ID
  - Create a few dummy pages under `/pages`
  -  See the tracking work

## Assignment 2
TASK: Review the structure of the mahad-al-tafsir repo and brainstorm how you would implement the tracking ID in this repo. Create the key steps/tasks that would have to be done below (Just in text/stub code)

**Comment by Nausheen701** [comment]
- create gtag.js file in lib folder 
- in gtag.js file, add tracking ID and pageview + event functions 
- create _document.js in content folder & add tracker to html
- create _app.js in content folder & add event handlers

**Comment by ismaelrumzan** [comment]
> * create gtag.js file in lib folder
> * in gtag.js file, add tracking ID and pageview + event functions
> * create _document.js in content folder & add tracker to html
> * create _app.js in content folder & add event handlers
This would work for a `Next.js` project
However, the docusaurus is different. You can use the following plug in:
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics

You can simply add the ID to the config file
https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-google-analytics#ex-config

**Comment by ismaelrumzan** [comment]
@Nausheen701 I'm going to close this issue - I implemented it in production here:
https://github.com/ismaelrumzan/mahad-al-tafsir/blob/main/docusaurus.config.js#L31
If you inspect the code on any page of https://tafsir.institute/, you will see this

![CleanShot 2022-08-13 at 15 09 21](https://user-images.githubusercontent.com/481891/184493460-b69459c9-ca09-4901-a054-243542fea428.png)
