### ISSUE TITLE
Video thumbnail list empty on load

### ISSUE THREAD

**Issue by ismaelrumzan** [ismaelrumzan/mahad-al-tafsir#4]
Example:
https://tafsir.institute/videos/%D8%AC%D9%85%D9%8A%D8%B9%20%D8%AF%D9%88%D8%B1%D8%A7%D8%AA%20%D8%A7%D9%84%D9%86%D8%AD%D9%88/%D8%A7%D9%84%D9%86%D8%AD%D9%88%20%D8%A7%D9%84%D9%88%D8%B8%D9%8A%D9%81%D9%8A

Only when you resize, the video thumbnail list shows up

**Comment by nuratun** [comment]
Opened #6 in regards to this bug
