### ISSUE TITLE
Playlist height function doesn't match video on first load

### ISSUE THREAD

**Issue by nqasid** [ismaelrumzan/mahad-al-tafsir#6]
The playlist on the side of the video is supposed to match the video height when it first loads. However, the user needs to resize the the browser window in order for the correct height to register. 

TODO: Look into integrating a YT playlist library, which may resolve this issue

**Comment by ismaelrumzan** [comment]
Moved to using drop-down https://github.com/ismaelrumzan/mahad-al-tafsir/pull/9
